emplist1 = list()
emplist2 = []
print(emplist1)
emplist1.append(9)
emplist1.append(10)
print(emplist1)
print(emplist2)
emplist2.extend(['a', 'b', 'c'])
print(emplist2)
e = emplist2.pop()
print(emplist2)
print(e)